name: Build and Download
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: python:alpine
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: /app

      - name: Build project
        working-directory: /app
        run: |
          pip install --upgrade pip &&
          pip install -r requirements.txt
          python main.py > output.txt

      - name: Create tarball
        working-directory: /app
        run: tar -czvf /tmp/build.tar.gz output.txt

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: build-tarball
          path: /tmp/build.tar.gz